import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Function to generate random password
function generateRandomPassword(length: number = 16): string {
  const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*';
  const values = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(values)
    .map((val) => charset[val % charset.length])
    .join('');
}

async function main() {
  console.log('🌱 Iniciando carga de datos...');

  // Crear usuario administrador
  const adminPassword = process.env.ADMIN_PASSWORD || 'admin123';
  const hashedPassword = await bcrypt.hash(adminPassword, 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@platamarcalderon.com' },
    update: {},
    create: {
      email: 'admin@platamarcalderon.com',
      name: 'Administrador Plata Mar',
      password: hashedPassword,
      phone: '+525529711016',
      role: 'ADMIN',
    },
  });

  console.log('✅ Usuario administrador creado:', admin.email);
  console.log('   Contraseña:', adminPassword);

  // Crear usuario de prueba (solo en desarrollo)
  if (process.env.NODE_ENV !== 'production') {
    const testUserPassword = 'test123';
    const userPassword = await bcrypt.hash(testUserPassword, 10);
    const user = await prisma.user.upsert({
      where: { email: 'cliente@ejemplo.com' },
      update: {},
      create: {
        email: 'cliente@ejemplo.com',
        name: 'Cliente de Prueba',
        password: userPassword,
        phone: '+525512345678',
        role: 'USER',
      },
    });

    console.log('✅ Usuario de prueba creado:', user.email);
    console.log('   Contraseña:', testUserPassword);
  }

  // Productos de Piezas Únicas - Plata Mar Calderón
  const products = [
    {
      name: 'Anillo de Plata con Turquesa',
      slug: 'anillo-plata-turquesa-1',
      description: 'Hermoso anillo de plata .925 con incrustación de turquesa natural. Pieza única hecha a mano.',
      price: 1200,
      image: '/img/products/pieza-1.jpg',
      images: ['/img/products/pieza-1.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Amatista',
      slug: 'anillo-plata-amatista-2',
      description: 'Elegante anillo de plata .925 con piedra amatista genuina. Diseño exclusivo.',
      price: 1350,
      image: '/img/products/pieza-2.jpg',
      images: ['/img/products/pieza-2.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo Ovalado de Plata',
      slug: 'anillo-ovalado-plata-3',
      description: 'Anillo de plata .925 con diseño ovalado y detalles artesanales únicos.',
      price: 980,
      image: '/img/products/pieza-3.jpg',
      images: ['/img/products/pieza-3.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Ónix',
      slug: 'anillo-plata-onix-4',
      description: 'Sofisticado anillo de plata .925 con piedra ónix natural. Acabado pulido.',
      price: 1150,
      image: '/img/products/pieza-4.jpg',
      images: ['/img/products/pieza-4.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo Artesanal de Plata',
      slug: 'anillo-artesanal-plata-5',
      description: 'Anillo de plata .925 con trabajo artesanal detallado. Pieza única.',
      price: 890,
      image: '/img/products/pieza-5.jpg',
      images: ['/img/products/pieza-5.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Coral',
      slug: 'anillo-plata-coral-6',
      description: 'Precioso anillo de plata .925 con incrustación de coral natural.',
      price: 1280,
      image: '/img/products/pieza-6.jpg',
      images: ['/img/products/pieza-6.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo Grabado de Plata',
      slug: 'anillo-grabado-plata-7',
      description: 'Anillo de plata .925 con grabados tradicionales mexicanos.',
      price: 950,
      image: '/img/products/pieza-7.jpg',
      images: ['/img/products/pieza-7.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Lapislázuli',
      slug: 'anillo-plata-lapislazuli-8',
      description: 'Anillo de plata .925 con piedra lapislázuli azul profundo.',
      price: 1420,
      image: '/img/products/pieza-8.jpg',
      images: ['/img/products/pieza-8.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo Circular de Plata',
      slug: 'anillo-circular-plata-9',
      description: 'Anillo de plata .925 con diseño circular minimalista.',
      price: 820,
      image: '/img/products/pieza-9.jpg',
      images: ['/img/products/pieza-9.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Oxidada',
      slug: 'anillo-plata-oxidada-10',
      description: 'Anillo de plata .925 con acabado oxidado estilo vintage.',
      price: 1050,
      image: '/img/products/pieza-10.jpg',
      images: ['/img/products/pieza-10.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Cuarzo',
      slug: 'anillo-plata-cuarzo-11',
      description: 'Anillo de plata .925 con cuarzo natural transparente.',
      price: 1180,
      image: '/img/products/pieza-11.jpg',
      images: ['/img/products/pieza-11.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo Tejido de Plata',
      slug: 'anillo-tejido-plata-12',
      description: 'Anillo de plata .925 con diseño tejido a mano.',
      price: 990,
      image: '/img/products/pieza-12.jpg',
      images: ['/img/products/pieza-12.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Jade',
      slug: 'anillo-plata-jade-13',
      description: 'Anillo de plata .925 con piedra de jade verde natural.',
      price: 1380,
      image: '/img/products/pieza-13.jpg',
      images: ['/img/products/pieza-13.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Filigrana',
      slug: 'anillo-plata-filigrana-14',
      description: 'Delicado anillo de plata .925 con trabajo de filigrana.',
      price: 1100,
      image: '/img/products/pieza-14.jpg',
      images: ['/img/products/pieza-14.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Granate',
      slug: 'anillo-plata-granate-15',
      description: 'Anillo de plata .925 con piedra granate rojo intenso.',
      price: 1320,
      image: '/img/products/pieza-15.jpg',
      images: ['/img/products/pieza-15.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo Rectangular de Plata',
      slug: 'anillo-rectangular-plata-16',
      description: 'Anillo de plata .925 con diseño rectangular moderno.',
      price: 880,
      image: '/img/products/pieza-16.jpg',
      images: ['/img/products/pieza-16.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Ámbar',
      slug: 'anillo-plata-ambar-17',
      description: 'Anillo de plata .925 con piedra de ámbar genuino.',
      price: 1450,
      image: '/img/products/pieza-17.jpg',
      images: ['/img/products/pieza-17.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Trenzado',
      slug: 'anillo-plata-trenzado-18',
      description: 'Anillo de plata .925 con diseño trenzado artesanal.',
      price: 920,
      image: '/img/products/pieza-18.jpg',
      images: ['/img/products/pieza-18.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Peridoto',
      slug: 'anillo-plata-peridoto-19',
      description: 'Anillo de plata .925 con piedra peridoto verde claro.',
      price: 1240,
      image: '/img/products/pieza-19.jpg',
      images: ['/img/products/pieza-19.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Martillado',
      slug: 'anillo-plata-martillado-20',
      description: 'Anillo de plata .925 con acabado martillado texturizado.',
      price: 850,
      image: '/img/products/pieza-20.jpg',
      images: ['/img/products/pieza-20.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Topacio',
      slug: 'anillo-plata-topacio-21',
      description: 'Anillo de plata .925 con piedra topacio azul brillante.',
      price: 1480,
      image: '/img/products/pieza-21.jpg',
      images: ['/img/products/pieza-21.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Sello',
      slug: 'anillo-plata-sello-22',
      description: 'Anillo de plata .925 estilo sello con superficie lisa para grabar.',
      price: 960,
      image: '/img/products/pieza-22.jpg',
      images: ['/img/products/pieza-22.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Citrino',
      slug: 'anillo-plata-citrino-23',
      description: 'Anillo de plata .925 con piedra citrino amarillo dorado.',
      price: 1260,
      image: '/img/products/pieza-23.jpg',
      images: ['/img/products/pieza-23.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Espiralado',
      slug: 'anillo-plata-espiral-24',
      description: 'Anillo de plata .925 con diseño en espiral único.',
      price: 910,
      image: '/img/products/pieza-24.jpg',
      images: ['/img/products/pieza-24.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Piedra Luna',
      slug: 'anillo-plata-piedra-luna-25',
      description: 'Anillo de plata .925 con piedra luna iridiscente.',
      price: 1390,
      image: '/img/products/pieza-25.jpg',
      images: ['/img/products/pieza-25.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Geométrico',
      slug: 'anillo-plata-geometrico-26',
      description: 'Anillo de plata .925 con diseño geométrico contemporáneo.',
      price: 870,
      image: '/img/products/pieza-26.jpg',
      images: ['/img/products/pieza-26.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Obsidiana',
      slug: 'anillo-plata-obsidiana-27',
      description: 'Anillo de plata .925 con piedra obsidiana negra brillante.',
      price: 1220,
      image: '/img/products/pieza-27.jpg',
      images: ['/img/products/pieza-27.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Vintage',
      slug: 'anillo-plata-vintage-28',
      description: 'Anillo de plata .925 con diseño inspirado en estilo vintage.',
      price: 1030,
      image: '/img/products/pieza-28.jpg',
      images: ['/img/products/pieza-28.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Aguamarina',
      slug: 'anillo-plata-aguamarina-29',
      description: 'Anillo de plata .925 con piedra aguamarina azul celeste.',
      price: 1520,
      image: '/img/products/pieza-29.jpg',
      images: ['/img/products/pieza-29.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Minimalista',
      slug: 'anillo-plata-minimalista-30',
      description: 'Anillo de plata .925 con diseño minimalista elegante.',
      price: 790,
      image: '/img/products/pieza-30.jpg',
      images: ['/img/products/pieza-30.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Rubí',
      slug: 'anillo-plata-rubi-31',
      description: 'Anillo de plata .925 con piedra rubí rojo intenso.',
      price: 1650,
      image: '/img/products/pieza-31.jpg',
      images: ['/img/products/pieza-31.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Bohemio',
      slug: 'anillo-plata-bohemio-32',
      description: 'Anillo de plata .925 con estilo bohemio y detalles étnicos.',
      price: 940,
      image: '/img/products/pieza-32.jpg',
      images: ['/img/products/pieza-32.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Zafiro',
      slug: 'anillo-plata-zafiro-33',
      description: 'Anillo de plata .925 con piedra zafiro azul profundo.',
      price: 1580,
      image: '/img/products/pieza-33.jpg',
      images: ['/img/products/pieza-33.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Tribal',
      slug: 'anillo-plata-tribal-34',
      description: 'Anillo de plata .925 con diseño tribal mexicano.',
      price: 890,
      image: '/img/products/pieza-34.jpg',
      images: ['/img/products/pieza-34.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Esmeralda',
      slug: 'anillo-plata-esmeralda-35',
      description: 'Anillo de plata .925 con piedra esmeralda verde vibrante.',
      price: 1720,
      image: '/img/products/pieza-35.jpg',
      images: ['/img/products/pieza-35.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Contemporáneo',
      slug: 'anillo-plata-contemporaneo-36',
      description: 'Anillo de plata .925 con diseño contemporáneo audaz.',
      price: 1020,
      image: '/img/products/pieza-36.jpg',
      images: ['/img/products/pieza-36.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Perla',
      slug: 'anillo-plata-perla-37',
      description: 'Anillo de plata .925 con perla natural cultivada.',
      price: 1350,
      image: '/img/products/pieza-37.jpg',
      images: ['/img/products/pieza-37.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Étnico',
      slug: 'anillo-plata-etnico-38',
      description: 'Anillo de plata .925 con diseño étnico artesanal.',
      price: 970,
      image: '/img/products/pieza-38.jpg',
      images: ['/img/products/pieza-38.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata con Cornalina',
      slug: 'anillo-plata-cornalina-39',
      description: 'Anillo de plata .925 con piedra cornalina naranja fuego.',
      price: 1290,
      image: '/img/products/pieza-39.jpg',
      images: ['/img/products/pieza-39.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
    {
      name: 'Anillo de Plata Clásico',
      slug: 'anillo-plata-clasico-40',
      description: 'Anillo de plata .925 con diseño clásico atemporal.',
      price: 840,
      image: '/img/products/pieza-40.jpg',
      images: ['/img/products/pieza-40.jpg'],
      category: 'piezas-unicas',
      inStock: true,
      stockQuantity: 1,
      rating: 5.0,
      reviewCount: 0,
    },
  ];

  for (const product of products) {
    const productData = {
      ...product,
      images: JSON.stringify(product.images),
    };
    const created = await prisma.product.upsert({
      where: { slug: product.slug },
      update: productData,
      create: productData,
    });
    console.log(`✅ Producto creado: ${created.name}`);
  }

  console.log('🎉 Base de datos cargada exitosamente!');
  console.log(`📦 Total de productos: ${products.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error al cargar datos:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
